services:
  db:
    image: k8s_languagegame_db:local
    container_name: k8s_languagegame_db
    environment:
      POSTGRES_USER: language_game
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: language_game
    ports:
      - "5432:5432"

  backend:
    image: k8s_languagegame_backend:local
    container_name: k8s_languagegame_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: language_game
      DB_USER: language_game
      DB_PASSWORD: secret
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_HOST: 0.0.0.0
      IMAGE_URL_PREFIX: ${IMAGE_URL_PREFIX}
      AUDIO_URL_PREFIX: ${AUDIO_URL_PREFIX}
      LICENSE_URL_PREFIX: ${LICENSE_URL_PREFIX}
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    image: k8s_languagegame_frontend:local
    container_name: k8s_languagegame_frontend
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_HOST: backend
    ports:
      - "8080:80"
    depends_on:
      - backend
